pipeline {
  agent {
    kubernetes {
      yaml: """
kind: Pod
spec:
  containers:
  - name: jnlp
    image: terraform-slave
    imagePullPolicy: Always
    tty: false
"""
    }
  }
  stages {
    stage('download terraform config') {
      steps {
        git(url: 'https://github.com/benchmarkconsulting/packer.git', branch: 'main')
      }
    }

    stage('terraform int') {
      steps {
        sh 'terraform int'
      }
    }
    stage('terraform validate') {
      steps {
        sh 'terraform validate'
      }
    }
    stage('terraform plan') {
      steps {
        sh 'terraform plan -vars-file=terraform.tfvars'
      }
    }
    stage('terraform apply') {
      steps {
        sh 'terraform apply -vars-file=terraform.tfvars -force'
      }
    }
  }
}
